spring:
  application:
    name: Hotel-Service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: Passcode@1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: configserver:http://localhost:8086
    
server:
  port: 8082


#eureka:
#  instance:
#    prefer-ip-address: true
#
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#
#    service-url:
#      defaultZone: http://localhost:8084/eureka
