spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shubhamboora/microservice-configuration
          clone-on-start: true



  application:
    name: CONFIG-SERVER


server:
  port: 8086


eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: http://localhost:8084/eureka